services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: fastapi-app:latest
    container_name: fastapi-app
    ports:
      - "8000:8000"  # ローカルポート:コンテナポート
    volumes:
      - ./app:/app/app  # ローカルコードをマウント（開発用）
    environment:
      - ENVIRONMENT=development
      - PYTHONPATH=/app
    env_file:
      - .env  # ローカル環境用設定
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    restart: unless-stopped
