"""add new_table and new_column

Revision ID: 00a79ef0dfd1
Revises: 10a0434c1056
Create Date: 2025-03-30 12:05:07.749168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00a79ef0dfd1'
down_revision: Union[str, None] = '10a0434c1056'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pnt_point_transactions', sa.Column('description', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pnt_point_transactions', 'description')
    # ### end Alembic commands ###
