"""add new_table and new_column

Revision ID: 0652eed05cdc
Revises: fe1b9bfee5f6
Create Date: 2025-05-09 11:17:26.718158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0652eed05cdc'
down_revision: Union[str, None] = 'fe1b9bfee5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user_invite_trackings', ['invited_user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_invite_trackings', type_='unique')
    # ### end Alembic commands ###
