"""add new_table and new_column

Revision ID: 089e620ff1b4
Revises: ed5e6d72f698
Create Date: 2025-07-09 19:21:22.474196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '089e620ff1b4'
down_revision: Union[str, None] = 'ed5e6d72f698'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cast_common_prof_ibfk_1', 'cast_common_prof', type_='foreignkey')
    op.create_foreign_key(None, 'cast_common_prof', 'users', ['tenant'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cast_common_prof', type_='foreignkey')
    op.create_foreign_key('cast_common_prof_ibfk_1', 'cast_common_prof', 'users', ['tenant'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
