"""add new_table and new_column

Revision ID: 0a3c0011a776
Revises: e36763f8243d
Create Date: 2025-06-14 15:39:31.110475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a3c0011a776'
down_revision: Union[str, None] = 'e36763f8243d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cast_withdrawal_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主キー：出金申請ID'),
    sa.Column('cast_id', sa.Integer(), nullable=False, comment='キャストID（users.id）'),
    sa.Column('amount', sa.Integer(), nullable=False, comment='出金申請額（ポイント＝円）'),
    sa.Column('status', sa.Enum('pending', 'approved', 'paid', 'rejected', 'cancelled', name='withdrawal_status_enum', create_constraint=True), nullable=False, comment='申請ステータス'),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='申請日時'),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True, comment='承認日時'),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True, comment='振込完了日時'),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True, comment='却下日時'),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True, comment='キャンセル日時'),
    sa.Column('point_transaction_id', sa.Integer(), nullable=True, comment='ポイント履歴（pnt_point_transactions.id）との連携'),
    sa.Column('account_snapshot', sa.JSON(), nullable=True, comment='申請時の口座情報（後から変更されても問題ないように）'),
    sa.Column('admin_memo', sa.Text(), nullable=True, comment='管理者メモ'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='論理削除フラグ'),
    sa.ForeignKeyConstraint(['cast_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['point_transaction_id'], ['pnt_point_transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table('cast_withdrawal_requests')
    # ### end Alembic commands ###
