"""add regular_amount and bonus_amount to withdrawal requests

Revision ID: 0ca95678160b
Revises: 0a3c0011a776
Create Date: 2025-06-15 13:18:57.215209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ca95678160b'
down_revision: Union[str, None] = '0a3c0011a776'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_foreign_key(None, 'cast_common_prof', 'users', ['tenant'], ['id'])  # Skip problematic FK
    op.add_column('cast_withdrawal_requests', sa.Column('regular_amount', sa.Integer(), nullable=True, comment='通常ポイント出金申請額'))
    op.add_column('cast_withdrawal_requests', sa.Column('bonus_amount', sa.Integer(), nullable=True, comment='ボーナスポイント出金申請額'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cast_withdrawal_requests', 'bonus_amount')
    op.drop_column('cast_withdrawal_requests', 'regular_amount')
    # op.drop_constraint(None, 'cast_common_prof', type_='foreignkey')  # Skip problematic FK
    # ### end Alembic commands ###
