"""add new_table and new_column

Revision ID: 246707db7f69
Revises: 0ba35698f28c
Create Date: 2025-04-02 08:14:40.519771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '246707db7f69'
down_revision: Union[str, None] = '0ba35698f28c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cast_common_prof', sa.Column('reservation_fee_deli', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cast_common_prof', 'reservation_fee_deli')
    # ### end Alembic commands ###
