"""add new_table and new_column

Revision ID: 4a2fab4a82ee
Revises: 6ffbc347ae89
Create Date: 2025-04-22 14:13:06.392838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a2fab4a82ee'
down_revision: Union[str, None] = '6ffbc347ae89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cast_identity_verification', sa.Column('bank_name', sa.String(length=100), nullable=True))
    op.add_column('cast_identity_verification', sa.Column('branch_name', sa.String(length=100), nullable=True))
    op.add_column('cast_identity_verification', sa.Column('branch_code', sa.String(length=10), nullable=True))
    op.add_column('cast_identity_verification', sa.Column('account_type', sa.String(length=20), nullable=True))
    op.add_column('cast_identity_verification', sa.Column('account_number', sa.String(length=20), nullable=True))
    op.add_column('cast_identity_verification', sa.Column('account_holder', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cast_identity_verification', 'account_holder')
    op.drop_column('cast_identity_verification', 'account_number')
    op.drop_column('cast_identity_verification', 'account_type')
    op.drop_column('cast_identity_verification', 'branch_code')
    op.drop_column('cast_identity_verification', 'branch_name')
    op.drop_column('cast_identity_verification', 'bank_name')
    # ### end Alembic commands ###
