"""add new_table and new_column

Revision ID: 4bb9952484ee
Revises: 0ca95678160b
Create Date: 2025-07-09 17:20:01.916994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bb9952484ee'
down_revision: Union[str, None] = '0ca95678160b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'cast_common_prof',
        'tenant',
        existing_type=sa.Integer(),
        nullable=True,
        existing_nullable=False
    )
    op.execute("UPDATE cast_common_prof SET tenant = NULL WHERE tenant NOT IN (SELECT id FROM users)")
    op.create_foreign_key(None, 'cast_common_prof', 'users', ['tenant'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cast_common_prof', type_='foreignkey')
    op.alter_column(
        'cast_common_prof',
        'tenant',
        existing_type=sa.Integer(),
        nullable=False,
        existing_nullable=True
    )
    # ### end Alembic commands ###
    op.add_column('pnt_details_rules', sa.Column('event_type', sa.String(length=255), nullable=False))
    op.add_column('pnt_details_rules', sa.Column('target_user_type', sa.Enum('referrer', 'referred', 'self', 'other', name='target_user_type_enum'), nullable=False))
    op.add_column('pnt_details_rules', sa.Column('condition_data', sa.JSON(), nullable=True))
    op.add_column('pnt_user_point_balances', sa.Column('pending_point_balance', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pnt_user_point_balances', 'pending_point_balance')
    op.drop_column('pnt_details_rules', 'condition_data')
    op.drop_column('pnt_details_rules', 'target_user_type')
    op.drop_column('pnt_details_rules', 'event_type')
    op.drop_constraint(None, 'cast_common_prof', type_='foreignkey')
    # ### end Alembic commands ###
