"""add new_table and new_column

Revision ID: be5087bc0a43
Revises: 089e620ff1b4
Create Date: 2025-07-29 01:07:44.394272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'be5087bc0a43'
down_revision: Union[str, None] = '089e620ff1b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cast_identity_verification', sa.Column('document_type', sa.String(length=50), nullable=True))
    op.drop_column('cast_identity_verification', 'branch_name')
    op.drop_column('cast_identity_verification', 'account_holder')
    op.drop_column('cast_identity_verification', 'bank_name')
    op.drop_column('cast_identity_verification', 'account_type')
    op.drop_column('cast_identity_verification', 'account_number')
    op.drop_column('cast_identity_verification', 'branch_code')
    op.alter_column('pnt_details_rules', 'transaction_type',
               existing_type=mysql.ENUM('reservation_payment', 'reservation_reward', 'event_bonus', 'coupon_bonus', 'buyin', 'referral_bonus_pending', 'referral_bonus_completed'),
               nullable=False)
    op.alter_column('pnt_details_rules', 'point_type',
               existing_type=mysql.ENUM('regular', 'bonus', 'pending'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pnt_details_rules', 'point_type',
               existing_type=mysql.ENUM('regular', 'bonus', 'pending'),
               nullable=True)
    op.alter_column('pnt_details_rules', 'transaction_type',
               existing_type=mysql.ENUM('reservation_payment', 'reservation_reward', 'event_bonus', 'coupon_bonus', 'buyin', 'referral_bonus_pending', 'referral_bonus_completed'),
               nullable=True)
    op.add_column('cast_identity_verification', sa.Column('branch_code', mysql.VARCHAR(length=10), nullable=True))
    op.add_column('cast_identity_verification', sa.Column('account_number', mysql.VARCHAR(length=20), nullable=True))
    op.add_column('cast_identity_verification', sa.Column('account_type', mysql.VARCHAR(length=20), nullable=True))
    op.add_column('cast_identity_verification', sa.Column('bank_name', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('cast_identity_verification', sa.Column('account_holder', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('cast_identity_verification', sa.Column('branch_name', mysql.VARCHAR(length=100), nullable=True))
    op.drop_column('cast_identity_verification', 'document_type')
    # ### end Alembic commands ###
