"""add new_table and new_column

Revision ID: e36763f8243d
Revises: 0652eed05cdc
Create Date: 2025-05-10 13:24:11.595106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e36763f8243d'
down_revision: Union[str, None] = '0652eed05cdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###


    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###


    # ### end Alembic commands ###
