"""add new_table and new_column

Revision ID: e36763f8243d
Revises: 0652eed05cdc
Create Date: 2025-05-10 13:24:11.595106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e36763f8243d'
down_revision: Union[str, None] = '0652eed05cdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cast_common_prof', sa.Column('tenant', sa.Integer(), nullable=False, comment='所属店舗ID（users.id）'))
    op.create_foreign_key(None, 'cast_common_prof', 'users', ['tenant'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cast_common_prof', type_='foreignkey')
    op.drop_column('cast_common_prof', 'tenant')
    # ### end Alembic commands ###
