"""make tenant nullable in 
  cast_common_prof

Revision ID: ed5e6d72f698
Revises: 4bb9952484ee
Create Date: 2025-07-09 17:41:01.788101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ed5e6d72f698'
down_revision: Union[str, None] = '4bb9952484ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cast_common_prof', 'tenant',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_comment='所属店舗ID（users.id）')

    # Clean up orphan tenant references before enforcing FK
    op.execute("""
        UPDATE cast_common_prof cp
        LEFT JOIN users u ON cp.tenant = u.id
        SET cp.tenant = NULL
        WHERE u.id IS NULL;
    """)

    # Add FK with ON DELETE SET NULL to maintain referential integrity in future deletions
    op.create_foreign_key(
        None,  # autogenerated constraint name
        'cast_common_prof',
        'users',
        ['tenant'],
        ['id'],
        ondelete='SET NULL'
    )
    op.add_column('pnt_details_rules', sa.Column('event_type', sa.String(length=255), nullable=False))
    op.add_column('pnt_details_rules', sa.Column('target_user_type', sa.Enum('referrer', 'referred', 'self', 'other', name='target_user_type_enum'), nullable=False))
    op.add_column('pnt_details_rules', sa.Column('condition_data', sa.JSON(), nullable=True))
    op.add_column('pnt_user_point_balances', sa.Column('pending_point_balance', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pnt_user_point_balances', 'pending_point_balance')
    op.drop_column('pnt_details_rules', 'condition_data')
    op.drop_column('pnt_details_rules', 'target_user_type')
    op.drop_column('pnt_details_rules', 'event_type')
    op.drop_constraint(None, 'cast_common_prof', type_='foreignkey')
    op.alter_column('cast_common_prof', 'tenant',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_comment='所属店舗ID（users.id）')
    # ### end Alembic commands ###
